import { F, SNACK, capitalize, type Fruit, type R } from "../dsl";

const out: R[] = [];
const fresh = (Object.values(F) as Fruit[]).filter((f) => f.key !== "compote");

const nuts = [
  { key: "amandes", id: "almonds", label: "amandes", en: "almonds" },
  { key: "noix", id: "walnuts", label: "noix", en: "walnuts" },
  { key: "cajou", id: "cashews", label: "noix de cajou", en: "cashews" },
];

for (const f of fresh) {
  for (const n of nuts) {
    out.push({
      id: `collation-${f.key}-${n.key}`,
      name: `${capitalize(f.name)} et ${n.label}`,
      meals: SNACK,
      ing: [...f.ing, [n.id, 15]],
      steps: [f.prep, `Servez avec une petite poignée de ${n.label} (environ 15 g).`],
      prep: 2,
      cook: 0,
      tags: ["no-cook", "quick", "lunchbox"],
      cuisine: "internationale",
      keeps: 0,
      img: `${f.img} ${n.en}`,
    });
  }
  out.push({
    id: `yaourt-${f.key}`,
    name: `Yaourt nature ${f.au}`,
    meals: SNACK,
    ing: [["yogurt", 125], ...f.ing],
    steps: [f.prep, "Ajoutez les fruits sur le yaourt."],
    prep: 2,
    cook: 0,
    tags: ["no-cook", "quick", "kid-friendly", "budget"],
    cuisine: "française",
    keeps: 0,
    img: `yogurt ${f.img}`,
  });
  out.push({
    id: `skyr-collation-${f.key}`,
    name: `Skyr ${f.au}`,
    meals: SNACK,
    ing: [["skyr", 120], ...f.ing],
    steps: [f.prep, "Ajoutez les fruits sur le skyr."],
    prep: 2,
    cook: 0,
    tags: ["no-cook", "quick", "high-protein"],
    cuisine: "nordique",
    keeps: 0,
    img: `skyr ${f.img}`,
  });
  out.push({
    id: `fromage-blanc-collation-${f.key}`,
    name: `Fromage blanc ${f.au}`,
    meals: SNACK,
    ing: [["fromage_blanc", 150], ...f.ing],
    steps: [f.prep, "Ajoutez les fruits sur le fromage blanc."],
    prep: 2,
    cook: 0,
    tags: ["no-cook", "quick", "kid-friendly"],
    cuisine: "française",
    keeps: 0,
    img: `fromage blanc ${f.img}`,
  });
  out.push({
    id: `soja-collation-${f.key}`,
    name: `Dessert au soja ${f.au}`,
    meals: SNACK,
    ing: [["soy_yogurt", 125], ...f.ing],
    steps: [f.prep, "Ajoutez les fruits sur le dessert au soja."],
    prep: 2,
    cook: 0,
    tags: ["no-cook", "quick"],
    cuisine: "internationale",
    keeps: 0,
    img: `soy yogurt ${f.img}`,
  });
}

for (const f of [F.apple, F.pear, F.banana, F.orange] as Fruit[]) {
  out.push({
    id: `chocolat-${f.key}`,
    name: `${capitalize(f.name)} et deux carrés de chocolat noir`,
    meals: SNACK,
    ing: [...f.ing, ["dark_chocolate", 15]],
    steps: [f.prep, "Servez avec deux carrés de chocolat noir."],
    prep: 2,
    cook: 0,
    tags: ["no-cook", "quick"],
    cuisine: "française",
    keeps: 0,
    img: `${f.img} dark chocolate`,
  });
}

const veggies = [
  { key: "carottes", id: "carrot", label: "carottes", en: "carrot sticks" },
  { key: "concombre", id: "cucumber", label: "concombre", en: "cucumber sticks" },
  { key: "poivron", id: "bell_pepper", label: "poivron", en: "bell pepper sticks" },
  { key: "radis", id: "radish", label: "radis", en: "radishes" },
];
for (const v of veggies) {
  out.push({
    id: `batonnets-${v.key}-houmous`,
    name: `Bâtonnets de ${v.label} et houmous`,
    meals: SNACK,
    ing: [[v.id, 150], ["hummus", 40]],
    steps: [`Lavez et coupez les ${v.label} en bâtonnets.`, "Servez avec le houmous."],
    prep: 5,
    cook: 0,
    tags: ["no-cook", "quick", "lunchbox", "light"],
    cuisine: "méditerranéenne",
    keeps: 0,
    img: `${v.en} hummus`,
  });
}

const singles: R[] = [
  {
    id: "compote-amandes",
    name: "Compote et amandes",
    meals: SNACK,
    ing: [["applesauce", 100], ["almonds", 15]],
    steps: ["Servez la compote avec une petite poignée d'amandes."],
    prep: 1,
    cook: 0,
    tags: ["no-cook", "quick", "lunchbox", "kid-friendly"],
    cuisine: "française",
    keeps: 0,
    img: "applesauce almonds",
  },
  {
    id: "galettes-riz-cacahuete",
    name: "Galettes de riz au beurre de cacahuète",
    meals: SNACK,
    ing: [["rice_cakes", 20], ["peanut_butter", 15], ["banana", 50]],
    steps: ["Tartinez les galettes de riz de beurre de cacahuète.", "Ajoutez quelques rondelles de banane."],
    prep: 2,
    cook: 0,
    tags: ["no-cook", "quick"],
    cuisine: "internationale",
    keeps: 0,
    img: "rice cakes peanut butter",
  },
  {
    id: "galettes-riz-fromage-frais",
    name: "Galettes de riz, fromage frais et concombre",
    meals: SNACK,
    ing: [["rice_cakes", 20], ["cream_cheese", 20], ["cucumber", 60]],
    steps: ["Tartinez les galettes de fromage frais.", "Ajoutez le concombre en fines rondelles."],
    prep: 3,
    cook: 0,
    tags: ["no-cook", "quick", "light"],
    cuisine: "internationale",
    keeps: 0,
    img: "rice cakes cream cheese cucumber",
  },
  {
    id: "comte-pain",
    name: "Comté et pain complet",
    meals: SNACK,
    ing: [["comte", 25], ["wholemeal_bread", 40]],
    steps: ["Servez le comté avec une tranche de pain complet."],
    prep: 1,
    cook: 0,
    tags: ["no-cook", "quick", "kid-friendly"],
    cuisine: "française",
    keeps: 0,
    img: "cheese bread",
  },
  {
    id: "comte-pomme",
    name: "Comté et pomme",
    meals: SNACK,
    ing: [["comte", 20], ["apple", 130]],
    steps: ["Coupez la pomme en quartiers et servez avec le comté."],
    prep: 2,
    cook: 0,
    tags: ["no-cook", "quick"],
    cuisine: "française",
    keeps: 0,
    img: "cheese apple",
  },
  {
    id: "oeuf-dur-tomates",
    name: "Œuf dur et tomates cerises",
    meals: SNACK,
    ing: [["egg", 1], ["cherry_tomato", 100]],
    steps: ["Faites cuire l'œuf 9 min dans l'eau bouillante, refroidissez-le et écalez-le.", "Servez avec les tomates cerises et une pincée de sel."],
    prep: 2,
    cook: 9,
    tags: ["quick", "high-protein", "lunchbox", "light"],
    cuisine: "française",
    keeps: 2,
    img: "boiled egg cherry tomatoes",
  },
  {
    id: "tartine-cacahuete",
    name: "Tartine au beurre de cacahuète",
    meals: SNACK,
    ing: [["wholemeal_bread", 40], ["peanut_butter", 15]],
    steps: ["Tartinez le pain de beurre de cacahuète."],
    prep: 1,
    cook: 0,
    tags: ["no-cook", "quick", "kid-friendly"],
    cuisine: "internationale",
    keeps: 0,
    img: "peanut butter toast",
  },
  {
    id: "energy-balls-dattes",
    name: "Energy balls dattes, amandes et cacao",
    desc: "À préparer une fois pour toute la semaine.",
    meals: SNACK,
    ing: [["dates", 25], ["almonds", 12], ["oats", 10], ["cocoa", 3]],
    steps: [
      "Dénoyautez les dattes.",
      "Mixez les dattes, les amandes, les flocons d'avoine et le cacao jusqu'à obtenir une pâte.",
      "Formez des boules de la taille d'une noix (environ 2 par portion).",
      "Conservez-les au réfrigérateur dans une boîte fermée jusqu'à une semaine.",
    ],
    prep: 15,
    cook: 0,
    tags: ["batch", "no-cook", "lunchbox"],
    eq: ["blender"],
    cuisine: "internationale",
    keeps: 7,
    img: "energy balls dates",
  },
  {
    id: "energy-balls-cacahuete",
    name: "Energy balls avoine et beurre de cacahuète",
    meals: SNACK,
    ing: [["oats", 20], ["peanut_butter", 12], ["honey", 6], ["dark_chocolate", 5]],
    steps: [
      "Mélangez les flocons d'avoine, le beurre de cacahuète, le miel et le chocolat haché.",
      "Formez des boules et placez-les 30 min au réfrigérateur.",
      "Se conservent une semaine au frais.",
    ],
    prep: 10,
    cook: 0,
    tags: ["batch", "no-cook", "lunchbox", "kid-friendly"],
    cuisine: "internationale",
    keeps: 7,
    img: "peanut butter energy balls",
  },
  {
    id: "pois-chiches-grilles",
    name: "Pois chiches grillés au paprika",
    meals: SNACK,
    ing: [["chickpeas", 80], ["olive_oil", 3], ["smoked_paprika", 0.5]],
    steps: [
      "Préchauffez le four à 200 °C.",
      "Égouttez, rincez et séchez soigneusement les pois chiches.",
      "Mélangez-les avec l'huile, le paprika et une pincée de sel.",
      "Enfournez 25 à 30 min en remuant à mi-cuisson, jusqu'à ce qu'ils soient croustillants.",
    ],
    prep: 5,
    cook: 30,
    tags: ["batch", "budget", "lunchbox"],
    eq: ["oven"],
    cuisine: "méditerranéenne",
    keeps: 4,
    img: "roasted chickpeas",
  },
  {
    id: "muffins-banane-avoine",
    name: "Muffins banane et avoine",
    meals: SNACK,
    ing: [["banana", 50], ["oats", 20], ["egg", 0.3], ["milk", 15], ["baking_powder", 1], ["raisins", 5]],
    steps: [
      "Préchauffez le four à 180 °C.",
      "Écrasez les bananes et mélangez-les avec les œufs et le lait.",
      "Ajoutez les flocons d'avoine, la levure et les raisins secs.",
      "Répartissez dans des moules à muffins et faites cuire 20 min.",
    ],
    prep: 10,
    cook: 20,
    tags: ["batch", "kid-friendly", "lunchbox"],
    eq: ["oven"],
    cuisine: "américaine",
    keeps: 4,
    img: "banana oat muffins",
  },
  {
    id: "fromage-blanc-miel-noix",
    name: "Fromage blanc, miel et noix",
    meals: SNACK,
    ing: [["fromage_blanc", 120], ["honey", 6], ["walnuts", 8]],
    steps: ["Versez le fromage blanc dans un bol.", "Ajoutez le miel et les noix émiettées."],
    prep: 2,
    cook: 0,
    tags: ["no-cook", "quick"],
    cuisine: "française",
    keeps: 0,
    img: "fromage blanc honey walnuts",
  },
  {
    id: "fruits-secs-amandes",
    name: "Abricots secs et amandes",
    meals: SNACK,
    ing: [["dried_apricot", 25], ["almonds", 12]],
    steps: ["Servez les abricots secs avec les amandes."],
    prep: 1,
    cook: 0,
    tags: ["no-cook", "quick", "lunchbox"],
    cuisine: "internationale",
    keeps: 0,
    img: "dried apricots almonds",
  },
];

out.push(...singles);

export const snacks = out;
